### Cadastrar um novo ativo (Ação)
POST http://localhost:8080/investments
Content-Type: application/json

{
  "type": "ACAO",
  "symbol": "BBAS3",
  "quantity": 100,
  "purchasePrice": 35.50,
  "purchaseDate": "2025-01-10"
}

### Cadastrar outro ativo (Cripto)
POST http://localhost:8080/investments
Content-Type: application/json

{
  "type": "CRIPTO",
  "symbol": "BTC",
  "quantity": 1,
  "purchasePrice": 25000.00,
  "purchaseDate": "2024-11-20"
}

### Listar todos os ativos da carteira (com cálculo de performance)
# @name getAllInvestments
GET http://localhost:8080/investments

### Atualizar o valor de mercado de um ativo
# Substitua {id} pelo ID de um ativo criado anteriormente
PATCH http://localhost:8080/investments/95ef3aaf-0492-4953-8323-e454036c2488/market-value
Content-Type: application/json

{
  "currentMarketPrice": 42.75
}

### Listar novamente para ver o lucro/prejuízo atualizado
GET http://localhost:8080/investments

### Remover um ativo da carteira
# Substitua {id} pelo ID de um ativo existente
DELETE http://localhost:8080/investments/95ef3aaf-0492-4953-8323-e454036c2488

### Resumo da carteira
GET http://localhost:8080/investments/summary